rule gatk4_BaseRecalibrator:
    # Preprocessing to do a base quality score recalibration with GATK
    # Generates recalibration table for Base Quality Score Recalibration (BQSR)
    input:
        knowns=lambda wildcards: ["%s%s%s%s" % (wildcards.prefix, config['dirs']['references'], known['file'], ending) for known in get_reference_knowns(wildcards.sample, SAMPLESHEETS, config, 'BaseRecalibrator') for ending in ['', ('' if known['file'].endswith('') else '')]],
	#gatkpackage="%s%sgatk4-4.1.9.0-py39_0.tar.bz2" % (config['dirs']['prefix'], config['dirs']['references']),
	references=lambda wildcards: ["%s%s%s%s" % (wildcards.prefix, config['dirs']['references'], get_reference_genome(wildcards.sample, SAMPLESHEETS, config)['file'], ending) for ending in config['endings_bwa']],
        #bam="{prefix}%s%s/{sample}.MBC.new.Hg38.srt.bam" % (config['dirs']['intermediate'], config['stepnames']['UMI']), ## V7
        bam= "{prefix}%s%s/Hg38/{sample}.UMI.target.nodup.srt.bam" % (config['dirs']['intermediate'], config['stepnames']['UMI']),
        bai= rules.samtools_index.output
	#bam="{prefix}%s%s/{sample}.Hg38.nodup.srt.bam" % (config['dirs']['intermediate'], config['stepnames']['nodup']),## V5
    output:
        "{prefix}%s%s/Hg38/{sample}.GATK4.Hg38.reCal.target.UMI.nodup.srt.table" % (config['dirs']['intermediate'], config['stepnames']['gatk4_BaseRecalibrator']),
    log:
        "{prefix}%s%s/Hg38/{sample}.log" % (config['dirs']['logs'], config['stepnames']['gatk4_BaseRecalibrator'])
    benchmark:
        "{prefix}%s%s/Hg38/{sample}.benchmark" % (config['dirs']['benchmarks'], config['stepnames']['gatk4_BaseRecalibrator'])
    conda:
        "envs/spike_gatk.yaml"
    threads:
        3
    params:
        knowns_settings=lambda wildcards: [' --known-sites %s%s%s ' % (wildcards.prefix, config['dirs']['references'], known['file']) for known in (get_reference_knowns(wildcards.sample, SAMPLESHEETS, config, 'BaseRecalibrator'))],
    shell:
        #'if [ $(gatk-register > /dev/null; echo "$?") -eq 1 ]; then rm -rf /tmp/gatk; gatk-register {input.gatkpackage} 2>> {log}; fi && '
        " gatk  --java-options"
        " -Xmx6g"#-XX:ParallelGCThreads={threads}"
        " BaseRecalibrator"
        " -I {input.bam}"
        " -R {input.references[0]}"
        "{params.knowns_settings}"
        " -O {output}"
        " 2>> {log} 1>&2"


rule gatk4_ApplyBQSR:
    # Apply base quality score recalibration
    # The goal of this procedure is to correct for systematic bias that affect the assignment of base quality scores by the sequencer
    #  recalibration table for Base Quality Score Recalibration (BQSR)
    input:
        references=lambda wildcards: ["%s%s%s%s" % (wildcards.prefix, config['dirs']['references'], get_reference_genome(wildcards.sample, SAMPLESHEETS, config)['file'], ending) for ending in config['endings_bwa']],
        table=rules.gatk4_BaseRecalibrator.output,
        Sbam="{prefix}%s%s/Hg38/{sample}.UMI.target.nodup.srt.bam" % (config['dirs']['intermediate'], config['stepnames']['UMI']), ## V7
	#Sbam="{prefix}%s%s/{sample}.Hg38.nodup.srt.bam" % (config['dirs']['intermediate'], config['stepnames']['nodup']),
	#table="{prefix}%s%s/{sample}.table" % (config['dirs']['intermediate'], config['stepnames']['gatk_BaseRecalibrator']),
        #table=rules.gatk_IndelRealigner.output.bam,
    output:
        "{prefix}%s%s/Hg38/{sample}.GATK4.Hg38.apBQSR.reCal.UMI.target.nodup.srt.bam" % (config['dirs']['intermediate'], config['stepnames']['gatk4_ApplyBQSR']),
    log:
        "{prefix}%s%s/Hg38/{sample}.log" % (config['dirs']['logs'], config['stepnames']['gatk4_ApplyBQSR'])
    benchmark:
        "{prefix}%s%s/Hg38/{sample}.benchmark" % (config['dirs']['benchmarks'], config['stepnames']['gatk4_ApplyBQSR'])
    conda:
        "envs/spike_gatk.yaml"
    threads:
        16
    shell:
        "gatk --java-options"
        " -Xmx16g" #-XX:ParallelGCThreads={threads}"
        " ApplyBQSR"
        " -I {input.Sbam}"
        " -R {input.references[0]}"
        " --bqsr-recal-file {input.table}"
        " -O {output}"
        " 2>> {log} 1>&2"


rule qualimap:
    input:
        bam=rules.gatk4_ApplyBQSR.output,
        #bai=rules.samtools_index2.output,
        exometrack=lambda wildcards: '%s%s%s' % (wildcards.prefix, config['dirs']['references'], get_reference_exometrack(wildcards.sample, SAMPLESHEETS, config, returnfield="qualimap_bed")),
    output:
        "{prefix}%s%s/Hg38/{sample}/qualimapReport.html" % (config['dirs']['intermediate'], config['stepnames']['qualimap']),
    log:
        "{prefix}%s%s/Hg38/{sample}.log" % (config['dirs']['logs'], config['stepnames']['qualimap']),
    benchmark:
        "{prefix}%s%s/Hg38/{sample}.benchmark" % (config['dirs']['benchmarks'], config['stepnames']['qualimap'])
    params:
        "{prefix}%s%s/Hg38/{sample}/" % (config['dirs']['intermediate'], config['stepnames']['qualimap']),
    threads:
        6
    shell:
        'qualimap bamqc'
        ' -bam {input.bam}'
        ' --feature-file {input.exometrack}'
        ' --collect-overlap-pairs'
        ' --genome-gc-distr HUMAN'
        ' -nr 5000'
        ' --java-mem-size=20G'
        ' -nt {threads}'
        ' -outformat HTML'
        ' -outdir {params}'
        ' > {log}'