rule trim:
    input:
        forward="{prefix}%s%s/{sample}_R1_UMI.fastq.gz" % (config['dirs']['intermediate'], config['stepnames']['rejoin_samples']),
        reverse="{prefix}%s%s/{sample}_R3_UMI.fastq.gz" % (config['dirs']['intermediate'], config['stepnames']['rejoin_samples'])
    output:
        pairedforward="{prefix}%s%s/Paired/{sample, .*?}_R1_UMI.fastq.gz" % (config['dirs']['intermediate'], config['stepnames']['trim']),
        pairedreverse="{prefix}%s%s/Paired/{sample, .*?}_R2_UMI.fastq.gz" % (config['dirs']['intermediate'], config['stepnames']['trim']),
    log:
        "{prefix}%s%s/{sample}.log" % (config['dirs']['logs'], config['stepnames']['trim'])
    benchmark:
        "{prefix}%s%s/{sample}.benchmark" % (config['dirs']['benchmarks'], config['stepnames']['trim'])
    conda:
      "envs/spike_trim.yaml"
    threads:
        16
    params:
        unpairedforward="{prefix}%s%s/Unpaired/{sample, .*?}_R1.fastq.gz" % (config['dirs']['intermediate'], config['stepnames']['trim']),
        unpairedreverse="{prefix}%s%s/Unpaired/{sample, .*?}_R2.fastq.gz" % (config['dirs']['intermediate'], config['stepnames']['trim'])
    shell:
        # if project directory for unpaired reads does not exist, we have to create it here since it is no regular snakemake output
        "mkdir -p `dirname {params.unpairedforward}` 2> {log}"
        " & java"
        " -Xmx4g"
        " -XX:ParallelGCThreads={threads}"
        " -jar ${{CONDA_PREFIX}}/share/trimmomatic-0.39-1/trimmomatic.jar"
        " PE -threads {threads} -phred33"
        " {input.forward}"
        " {input.reverse}"
        " {output.pairedforward}"
        " {params.unpairedforward}"
        " {output.pairedreverse}"
        " {params.unpairedreverse}"
        " ILLUMINACLIP:${{CONDA_PREFIX}}/share/trimmomatic-0.39-1/adapters/TruSeq3-PE.fa:2:30:10 CROP:149 LEADING:10 TRAILING:10 SLIDINGWINDOW:4:15 MINLEN:54"
        " >> {log} 2>&1"